#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Jeff Stokes"
email = "jeffecu88@gmail.com"

[aliases]
df = ["diff"]
ph = ["git", "push"]
fetch = ["git", "fetch"]

[ui]
default-command = "log"
