#!/bin/bash

set -e

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install tmux

brew install reattach-to-user-namespace

brew cask install emacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

git clone git@github.com:olivierverdier/zsh-git-prompt.git ~/.zsh/git-prompt
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

brew install rg
brew install cmake
brew install tree
brew install maven
brew install wget
brew install zsh
brew install ruby
brew install zsh-syntax-highlighting

curl -sSL https://get.haskellstack.org/ | sh

gem install git-smart

chsh -s $(which zsh)

ruby setup.rb
