#!/bin/bash
cd ~/Dotfiles/

#install tmux
brew install tmux

echo "installing reattach-to-user-namespace"
brew install reattach-to-user-namespace

echo "updating vim"
brew install https://raw.github.com/AndrewVos/homebrew-alt/master/duplicates/vim.rb

echo "installing vundle"
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

echo "installing oh-my-zsh"
./installer/oh-my-zsh.install

echo "linking dot files"
ruby setup.rb
