#!/bin/bash

set -e

if ! command -v brew >/dev/null 2>&1; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

[ ! -d ~/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

brew install tmux
if [[ "$OSTYPE" == darwin* ]]; then
  brew install reattach-to-user-namespace
fi
brew install rg
brew install cmake
brew install tree
brew install maven
brew install wget
brew install fish
brew install ruby
brew install neovim

ruby setup.rb

if command -v fish >/dev/null 2>&1; then
  fish -c "type -q fisher || (curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher)"
  fish -c "fisher update"
fi
